/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabajo.so;

/**
 *
 * @author Nicolas
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraDeHerramientas = new javax.swing.JToolBar();
        agregarProcesoBtn = new javax.swing.JButton();
        panelPestañas = new javax.swing.JTabbedPane();
        panelFIFO = new javax.swing.JScrollPane();
        panelRoundRobin = new javax.swing.JScrollPane();
        panelSJF = new javax.swing.JScrollPane();
        panelSTRF = new javax.swing.JScrollPane();
        panelExpulsivo = new javax.swing.JScrollPane();
        panelNoExpulsivo = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador de procesos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        barraDeHerramientas.setRollover(true);

        agregarProcesoBtn.setText("Agregar procesos");
        agregarProcesoBtn.setFocusable(false);
        agregarProcesoBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregarProcesoBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agregarProcesoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProcesoBtnActionPerformed(evt);
            }
        });
        barraDeHerramientas.add(agregarProcesoBtn);

        panelPestañas.addTab("FIFO", panelFIFO);
        panelPestañas.addTab("Round Robin", panelRoundRobin);
        panelPestañas.addTab("SJF", panelSJF);
        panelPestañas.addTab("STRF", panelSTRF);
        panelPestañas.addTab("Expulsivo", panelExpulsivo);
        panelPestañas.addTab("No Expulsivo", panelNoExpulsivo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraDeHerramientas, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPestañas)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(barraDeHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPestañas, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarProcesoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProcesoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarProcesoBtnActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarProcesoBtn;
    private javax.swing.JToolBar barraDeHerramientas;
    private javax.swing.JScrollPane panelExpulsivo;
    private javax.swing.JScrollPane panelFIFO;
    private javax.swing.JScrollPane panelNoExpulsivo;
    private javax.swing.JTabbedPane panelPestañas;
    private javax.swing.JScrollPane panelRoundRobin;
    private javax.swing.JScrollPane panelSJF;
    private javax.swing.JScrollPane panelSTRF;
    // End of variables declaration//GEN-END:variables
}
